emails = {
    "gmail": "google",
    "att.net": "att",
    "twc.com": "spectrum",
    "scranton.edu": "other",
    "netzero.net": "other",
    "optonline.net": "other",
    "comcast.net": "other",
    "cfl.rr.com": "other",
    "sc.rr.com": "other",
    "suddenlink.net": "other",
    "windstream.net": "other",
    "gmx.de": "other",
    "earthlink.net": "other",
    "servicios-ta.com": "other",
    "bellsouth.net": "other",
    "web.de": "other",
    "mail.com": "other",
    "cableone.net": "other",
    "roadrunner.com": "other",
    "protonmail.com": "other",
    "anonymous.com": "other",
    "juno.com": "other",
    "ptd.net": "other",
    "netzero.com": "other",
    "cox.net": "other",
    "hotmail.co.uk": "microsoft",
    "yahoo.com.mx": "yahoo",
    "yahoo.fr": "yahoo",
    "yahoo.es": "yahoo",
    "charter.net": "spectrum",
    "live.com": "microsoft",
    "aim.com": "aol",
    "hotmail.de": "microsoft",
    "centurylink.net": "centurylink",
    "gmail.com": "google",
    "me.com": "apple",
    "hotmail.com": "microsoft",
    "hotmail.fr": "microsoft",
    "outlook.es": "microsoft",
    "yahoo.co.jp": "yahoo",
    "yahoo.de": "yahoo",
    "live.fr": "microsoft",
    "verizon.net": "yahoo",
    "msn.com": "microsoft",
    "q.com": "centurylink",
    "prodigy.net.mx": "att",
    "frontier.com": "yahoo",
    "rocketmail.com": "yahoo",
    "sbcglobal.net": "att",
    "frontiernet.net": "yahoo",
    "ymail.com": "yahoo",
    "outlook.com": "microsoft",
    "embarqmail.com": "centurylink",
    "hotmail.es": "microsoft",
    "mac.com": "apple",
    "yahoo.co.uk": "yahoo",
    "yahoo.com": "yahoo",
    "live.com.mx": "microsoft",
    "aol.com": "aol",
    "icloud.com": "apple",
}

suspicious_null_cols = [
    "R_emaildomain",
    "id_02",
    "id_15",
    "id_35",
    "id_36",
    "id_37",
    "id_38",
    "id_11",
    "id_28",
    "id_29",
    "DeviceType",
    "id_01",
    "id_12",
    "id_31",
    "id_05",
    "id_06",
    "V169",
    "V170",
    "V171",
    "V174",
    "V175",
    "V180",
    "V184",
    "V185",
    "V188",
    "V189",
    "V194",
    "V195",
    "V197",
    "V198",
]

us_emails = ["gmail", "net", "edu"]

cat_cols = [
    "id_12",
    "id_13",
    "id_14",
    "id_15",
    "id_16",
    "id_17",
    "id_18",
    "id_19",
    "id_20",
    "id_21",
    "id_22",
    "id_23",
    "id_24",
    "id_25",
    "id_26",
    "id_27",
    "id_28",
    "id_29",
    "id_30",
    "id_31",
    "id_32",
    "id_33",
    "id_34",
    "id_35",
    "id_36",
    "id_37",
    "id_38",
    "DeviceType",
    "DeviceInfo",
    "ProductCD",
    "card4",
    "card6",
    "M4",
    "P_emaildomain",
    "R_emaildomain",
    "card1",
    "card2",
    "card3",
    "card5",
    "addr1",
    "addr2",
    "M1",
    "M2",
    "M3",
    "M5",
    "M6",
    "M7",
    "M8",
    "M9",
    "P_emaildomain",
    "R_emaildomain",
    "P_emaildomain_bin",
    "P_emaildomain_suffix",
    "R_emaildomain_bin",
    "R_emaildomain_suffix",
    "uid1",
    "uid2",
    "uid3",
    "device_os",
    "device_browser",
    "browser_version",
    "card1_card2",
]

te_cols = ["card1", "addr1", "uid1", "uid2", "P_emaildomain", "R_emaildomain"]
